### ISSUE TITLE
Using too many RAM memory

### ISSUE THREAD

**Issue by leandrosimoes** [leandrosimoes/ls-doc-maker#1]
During the doc development, the app is incressing the use of RAM. Maybe is because of the localStorage.

**Comment by edelciomolina** [comment]
Try change localStorage for file system, maybe create a timeout to save after some seconds after changes can fix it.

**Comment by leandrosimoes** [comment]
Closing because the issue was solved after force a garbage colector (Tks to @edelciomolina), changing some knockoutjs computeds to pureComputeds and implementing a dispose for ACE Editor in knockoutjs custom bindings.
